version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: auth-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: authdb
    volumes:
      - auth-mysql-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p password"]
      interval: 10s
      timeout: 5s
      retries: 5

  authservice:
    build: .
    container_name: authservice
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  auth-mysql-data: